* fxruby-enhancement

  The fxruby library is an excellent wrapper for the FOX toolkit. However, it reflects the
  C++-ness of FOX, rather than being more Ruby-like. As such, creating composed objects with
  it tends to be rather ugly and cumbersome.

  fxruby-enhancement is a wrapper for the wrapper, to "rubyfy" it and make it more easy to 
  use for Rubyists. 

  fxruby-enhancement is basically a DSL of sorts, and every effort has been taken to make 
  it intuitive to use. Once you get the hang of it, you should be able to look at the FXRuby
  API documentation and infer the DSL construct for fxruby-enhancement.

** TODO Examples
** TODO Documentation
** TODO Release Notes
** TODO Known Issues

** Contributing to fxruby-enhancement
 
   - Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
   - Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
   - Fork the project.
   - Start a feature/bugfix branch.
   - Commit and push until you are happy with your contribution.
   - Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
   - Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2016-2017 Fred Mitchell. See LICENSE.txt for
   further details.
