==begin rdoc

NOTE WELL:
  This file is generated by fxruby-enhancement.
  Do NOT modify this file. Modify the template
  file instead!!!!

==end


   #FX4Splitter < FXComposite
   
      
         #{:p=>nil, :opts=>"FOURSPLITTER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
         #{:p=>nil, :tgt=>nil, :sel=>nil, :opts=>"FOURSPLITTER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FX7Segment < FXFrame
   
      
         #{:p=>nil, :text=>nil, :opts=>"SEVENSEGMENT_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXAccelTable < FXObject
   
      
         #   
      
   

   #FXEvent < 
   
      #No initializer
   

   #FXApp < FXObject
   
      
         #{:appName=>"\"Application\"", :vendorName=>"\"FoxDefault\""}   
      
   

   #FXArrowButton < FXFrame
   
      
         #{:parent=>nil, :target=>"nil", :selector=>"0", :opts=>"ARROW_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXBMPIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"Fox.FXRGB(192", :"192"=>nil}   
      
   

   #FXBMPImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXBitmap < FXDrawable
   
      
         #{:app=>nil, :pixels=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXBitmapFrame < FXFrame
   
      
         #{:p=>nil, :bmp=>nil, :opts=>"FRAME_SUNKEN|FRAME_THICK", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXBitmapView < FXScrollArea
   
      
         #{:p=>nil, :bmp=>"nil", :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXButton < FXLabel
   
      
         #{:parent=>nil, :text=>nil, :icon=>"nil", :target=>"nil", :selector=>"0", :opts=>"BUTTON_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXCURCursor < FXCursor
   
      
         #{:app=>nil, :pixels=>nil}   
      
   

   #FXCanvas < FXWindow
   
      
         #{:parent=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXCheckButton < FXLabel
   
      
         #{:parent=>nil, :text=>nil, :target=>"nil", :selector=>"0", :opts=>"CHECKBUTTON_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXChoiceBox < FXDialogBox
   
      
         #{:owner=>nil, :caption=>nil, :text=>nil, :icon=>nil, :choices=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXColorBar < FXFrame
   
      
         #{:parent=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXColorDialog < FXDialogBox
   
      
         #{:owner=>nil, :title=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXColorItem < FXListItem
   
      
         #{:text=>nil, :clr=>nil, :data=>"nil"}   
      
   

   #FXColorList < FXList
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"LIST_BROWSESELECT", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXColorRing < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXColorSelector < FXPacker
   
      
         #{:parent=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXColorWell < FXFrame
   
      
         #{:parent=>nil, :color=>"0", :target=>"nil", :selector=>"0", :opts=>"COLORWELL_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXColorWheel < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXComboBox < FXPacker
   
      
         #{:p=>nil, :cols=>nil, :target=>"nil", :selector=>"0", :opts=>"COMBOBOX_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXComposite < FXWindow
   
      
         #{:parent=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXCursor < FXId
   
      
         #{:a=>nil, :curid=>"CURSOR_ARROW"}   
      
         #{:a=>nil, :pix=>nil, :width=>"32", :height=>"32", :hotX=>"-1", :hotY=>"-1"}   
      
         #{:a=>nil, :pixels=>nil, :width=>"32", :height=>"32", :hotX=>"-1", :hotY=>"-1"}   
      
   

   #FXSegment < 
   
      #No initializer
   

   #FXArc < 
   
      #No initializer
   

   #FXDC < 
   
      
         #{:app=>nil}   
      
   

   #FXPSBounds < 
   
      
         #   
      
   

   #FXPrinter < 
   
      
         #   
      
   

   #FXDCPrint < FXDC
   
      
         #{:app=>nil}   
      
   

   #FXDCWindow < FXDC
   
      
         #{:drawable=>nil, :event=>"nil"}   
      
   

   #FXDataTarget < FXObject
   
      
         #{:value=>"nil", :target=>"nil", :selector=>"0"}   
      
   

   #FXDebugTarget < FXObject
   
      
         #   
      
   

   #FXDelegator < FXObject
   
      
         #{:delegate=>"nil"}   
      
   

   #FXDial < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"DIAL_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXDialogBox < FXTopWindow
   
      
         #{:owner=>nil, :title=>nil, :opts=>"DECOR_TITLE|DECOR_BORDER", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"10", :padRight=>"10", :padTop=>"10", :padBottom=>"10", :hSpacing=>"4", :vSpacing=>"4"}   
      
   

   #FXDict < FXObject
   
      
         #   
      
   

   #FXDirBox < FXTreeListBox
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_SUNKEN|FRAME_THICK|TREELISTBOX_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXDirDialog < FXDialogBox
   
      
         #{:owner=>nil, :name=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"500", :height=>"300"}   
      
   

   #FXDirItem < FXTreeItem
   
      
         #{:text=>nil, :oi=>"nil", :ci=>"nil", :data=>"nil"}   
      
   

   #FXDirList < FXTreeList
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXDirSelector < FXPacker
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXDockBar < FXPacker
   
      
         #{:p=>nil, :q=>nil, :opts=>"LAYOUT_TOP|LAYOUT_LEFT|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
         #{:p=>nil, :opts=>"LAYOUT_TOP|LAYOUT_LEFT|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXDockHandler < FXFrame
   
      
         #{:p=>nil, :tgt=>nil, :sel=>nil, :opts=>nil, :x=>nil, :y=>nil, :w=>nil, :h=>nil, :pl=>nil, :pr=>nil, :pt=>nil, :pb=>nil}   
      
   

   #FXDockSite < FXPacker
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0", :hSpacing=>"0", :vSpacing=>"0"}   
      
   

   #FXDockTitle < FXDockHandler
   
      
         #{:p=>nil, :text=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_NORMAL|JUSTIFY_CENTER_X|JUSTIFY_CENTER_Y", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXDocument < FXObject
   
      
         #   
      
   

   #FXDragCorner < FXWindow
   
      
         #{:p=>nil}   
      
   

   #FXDrawable < FXId
   
      #No initializer
   

   #FXDriveBox < FXListBox
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_SUNKEN|FRAME_THICK|LISTBOX_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXExtentd < 
   
      
         #   
      
         #{:ext=>nil}   
      
         #{:lo=>nil, :hi=>nil}   
      
         #{:xlo=>nil, :xhi=>nil, :ylo=>nil, :yhi=>nil}   
      
   

   #FXExtentf < 
   
      
         #   
      
         #{:ext=>nil}   
      
         #{:lo=>nil, :hi=>nil}   
      
         #{:xlo=>nil, :xhi=>nil, :ylo=>nil, :yhi=>nil}   
      
   

   #FXFileDialog < FXDialogBox
   
      
         #{:owner=>nil, :name=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"500", :height=>"300"}   
      
   

   #FXFileAssoc < 
   
      
         #   
      
   

   #FXFileDict < FXDict
   
      
         #{:app=>nil, :db=>"nil"}   
      
   

   #FXFileItem < FXIconItem
   
      
         #{:text=>nil, :bi=>"nil", :mi=>"nil", :ptr=>"nil"}   
      
   

   #FXFileList < FXIconList
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXFileSelector < FXPacker
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXFileStream < FXStream
   
      
         #{:cont=>"nil"}   
      
   

   #FXFoldingItem < FXObject
   
      
         #{:text=>nil, :openIcon=>"nil", :closedIcon=>"nil", :data=>"nil"}   
      
   

   #FXFoldingList < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"TREELIST_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXFontDesc < 
   
      
         #   
      
   

   #FXFont < FXId
   
      
         #{:a=>nil, :fontDesc=>nil}   
      
         #{:a=>nil, :face=>nil, :size=>nil, :weight=>"FXFont::Normal", :slant=>"Font::Straight", :encoding=>"FONTENCODING_DEFAULT", :setWidth=>"FXFont::NonExpanded", :hints=>"0"}   
      
         #{:a=>nil, :string=>nil}   
      
   

   #FXFontDialog < FXDialogBox
   
      
         #{:owner=>nil, :name=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"600", :height=>"380"}   
      
   

   #FXFontSelector < FXPacker
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXFrame < FXWindow
   
      
         #{:parent=>nil, :opts=>"FRAME_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXGIFCursor < FXCursor
   
      
         #{:a=>nil, :pix=>nil, :hx=>"-1", :hy=>"-1"}   
      
   

   #FXGIFIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXGIFImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXGLCanvas < FXCanvas
   
      
         #{:parent=>nil, :vis=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
         #{:parent=>nil, :vis=>nil, :sharegroup=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXGLContext < FXId
   
      
         #{:app=>nil, :visual=>nil, :other=>"nil"}   
      
   

   #FXGLObject < FXObject
   
      
         #   
      
   

   #FXGLShape < FXGLObject
   
      
         #{:x=>nil, :y=>nil, :z=>nil, :opts=>nil, :front=>"nil", :back=>"nil"}   
      
   

   #FXViewport < 
   
      
         #   
      
   

   #FXLight < 
   
      
         #   
      
   

   #FXMaterial < 
   
      
         #   
      
   

   #FXGLViewer < FXGLCanvas
   
      
         #{:p=>nil, :vis=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
         #{:p=>nil, :vis=>nil, :sharegroup=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXGLVisual < FXVisual
   
      
         #{:app=>nil, :flags=>nil}   
      
   

   #FXGradient < 
   
      #No initializer
   

   #FXGradientBar < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXGroupBox < FXPacker
   
      
         #{:parent=>nil, :text=>nil, :opts=>"GROUPBOX_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXHeaderItem < FXObject
   
      
         #{:text=>nil, :ic=>"nil", :s=>"0", :ptr=>"nil"}   
      
   

   #FXHeader < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"HEADER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXHorizontalFrame < FXPacker
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXICOIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXICOImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXIcon < FXImage
   
      
         #{:app=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXIconDict < FXDict
   
      #No initializer
   

   #FXIconItem < FXObject
   
      
         #{:text=>nil, :bigIcon=>"nil", :miniIcon=>"nil", :data=>"nil"}   
      
   

   #FXIconList < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"ICONLIST_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXIconSource < FXObject
   
      
         #{:app=>nil}   
      
   

   #FXId < FXObject
   
      #No initializer
   

   #FXImage < FXDrawable
   
      
         #{:a=>nil, :pixels=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXImageFrame < FXFrame
   
      
         #{:p=>nil, :img=>nil, :opts=>"FRAME_SUNKEN|FRAME_THICK", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXImageView < FXScrollArea
   
      
         #{:p=>nil, :img=>"nil", :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXInputDialog < FXDialogBox
   
      
         #{:owner=>nil, :caption=>nil, :label=>nil, :icon=>"nil", :opts=>"INPUTDIALOG_STRING", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXJPGIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1", :quality=>"75"}   
      
   

   #FXJPGImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1", :quality=>"75"}   
      
   

   #FXKnob < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"KNOB_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXLabel < FXFrame
   
      
         #{:parent=>nil, :text=>nil, :icon=>"nil", :opts=>"LABEL_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXListItem < FXObject
   
      
         #{:text=>nil, :icon=>"nil", :data=>"nil"}   
      
   

   #FXList < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"LIST_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXListBox < FXPacker
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_SUNKEN|FRAME_THICK|LISTBOX_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXMDIDeleteButton < FXButton
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_RAISED", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMDIRestoreButton < FXButton
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_RAISED", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMDIMaximizeButton < FXButton
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_RAISED", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMDIMinimizeButton < FXButton
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_RAISED", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMDIWindowButton < FXMenuButton
   
      
         #{:p=>nil, :pup=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMDIMenu < FXMenuPane
   
      
         #{:owner=>nil, :target=>"nil"}   
      
   

   #FXMDIChild < FXComposite
   
      
         #{:p=>nil, :name=>nil, :ic=>"nil", :pup=>"nil", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMDIClient < FXComposite
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXMainWindow < FXTopWindow
   
      
         #{:app=>nil, :title=>nil, :icon=>"nil", :miniIcon=>"nil", :opts=>"DECOR_ALL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0", :hSpacing=>"4", :vSpacing=>"4"}   
      
   

   #FXMatrix < FXPacker
   
      
         #{:parent=>nil, :n=>"1", :opts=>"MATRIX_BY_ROWS", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXMemoryBuffer < 
   
      
         #{:data=>nil}   
      
   

   #FXMemoryStream < FXStream
   
      
         #{:cont=>"nil"}   
      
   

   #FXMenuBar < FXToolBar
   
      
         #{:p=>nil, :q=>nil, :opts=>"LAYOUT_TOP|LAYOUT_LEFT|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
         #{:p=>nil, :opts=>nil, :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXMenuButton < FXLabel
   
      
         #{:parent=>nil, :text=>nil, :icon=>"nil", :popupMenu=>"nil", :opts=>"JUSTIFY_NORMAL|ICON_BEFORE_TEXT|MENUBUTTON_DOWN", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING"}   
      
   

   #FXMenuCaption < FXWindow
   
      
         #{:parent=>nil, :text=>nil, :icon=>"nil", :opts=>"0"}   
      
   

   #FXMenuCascade < FXMenuCaption
   
      
         #{:parent=>nil, :text=>nil, :icon=>"nil", :popupMenu=>"nil", :opts=>"0"}   
      
   

   #FXMenuCheck < FXMenuCommand
   
      
         #{:p=>nil, :text=>nil, :target=>"nil", :selector=>"0", :opts=>"0"}   
      
   

   #FXMenuCommand < FXMenuCaption
   
      
         #{:p=>nil, :text=>nil, :ic=>"nil", :target=>"nil", :selector=>"0", :opts=>"0"}   
      
   

   #FXMenuPane < FXPopup
   
      
         #{:owner=>nil, :opts=>"0"}   
      
   

   #FXMenuRadio < FXMenuCommand
   
      
         #{:p=>nil, :text=>nil, :target=>"nil", :selector=>"0", :opts=>"0"}   
      
   

   #FXMenuSeparator < FXWindow
   
      
         #{:parent=>nil, :opts=>"0"}   
      
   

   #FXMenuTitle < FXMenuCaption
   
      
         #{:parent=>nil, :text=>nil, :icon=>"nil", :popupMenu=>"nil", :opts=>"0"}   
      
   

   #FXMessageBox < FXDialogBox
   
      
         #{:owner=>nil, :caption=>nil, :text=>nil, :ic=>"nil", :opts=>"0", :x=>"0", :y=>"0"}   
      
   

   #FXObject < 
   
      #No initializer
   

   #FXOption < FXLabel
   
      
         #{:p=>nil, :text=>nil, :ic=>"nil", :target=>"nil", :selector=>"0", :opts=>"JUSTIFY_NORMAL|ICON_BEFORE_TEXT", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXOptionMenu < FXLabel
   
      
         #{:p=>nil, :pup=>"nil", :opts=>"JUSTIFY_NORMAL|ICON_BEFORE_TEXT", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXPCXIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXPCXImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXPNGIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXPNGImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXPPMIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXPPMImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXPacker < FXComposite
   
      
         #{:parent=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXPicker < FXButton
   
      
         #{:p=>nil, :text=>nil, :ic=>"nil", :target=>"nil", :selector=>"0", :opts=>"BUTTON_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXPopup < FXShell
   
      
         #{:owner=>nil, :opts=>"POPUP_VERTICAL|FRAME_RAISED|FRAME_THICK", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXPrintDialog < FXDialogBox
   
      
         #{:owner=>nil, :name=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXProgressBar < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"PROGRESSBAR_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXProgressDialog < FXDialogBox
   
      
         #{:owner=>nil, :caption=>nil, :label=>nil, :opts=>"PROGRESSDIALOG_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXQuatd < FXVec4d
   
      
         #   
      
         #{:axis=>nil, :phi=>"0.0"}   
      
         #{:x=>nil, :y=>nil, :z=>nil, :w=>nil}   
      
         #{:floats=>nil}   
      
         #{:roll=>nil, :pitch=>nil, :yaw=>nil}   
      
         #{:ex=>nil, :ey=>nil, :ez=>nil}   
      
   

   #FXQuatf < FXVec4f
   
      
         #   
      
         #{:axis=>nil, :phi=>"0.0"}   
      
         #{:roll=>nil, :pitch=>nil, :yaw=>nil}   
      
         #{:ex=>nil, :ey=>nil, :ez=>nil}   
      
         #{:mat=>nil}   
      
         #{:x=>nil, :y=>nil, :z=>nil, :w=>nil}   
      
   

   #FXRGBIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXRGBImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXRadioButton < FXLabel
   
      
         #{:parent=>nil, :text=>nil, :target=>"nil", :selector=>"0", :opts=>"RADIOBUTTON_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXRanged < 
   
      
         #{:xlo=>"0.0", :xhi=>"0.0", :ylo=>"0.0", :yhi=>"0.0", :zlo=>"0.0", :zhi=>"0.0"}   
      
         #{:bounds=>nil}   
      
         #{:sphere=>nil}   
      
   

   #FXRangef < 
   
      
         #{:xlo=>"0.0", :xhi=>"0.0", :ylo=>"0.0", :yhi=>"0.0", :zlo=>"0.0", :zhi=>"0.0"}   
      
         #{:bounds=>nil}   
      
         #{:sphere=>nil}   
      
   

   #FXRealSlider < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"REALSLIDER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXRealSpinner < FXPacker
   
      
         #{:p=>nil, :cols=>nil, :target=>"nil", :selector=>"0", :opts=>"REALSPIN_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXRecentFiles < FXObject
   
      
         #   
      
         #{:a=>nil}   
      
         #{:a=>nil, :gp=>nil, :target=>"nil", :selector=>"0"}   
      
   

   #FXRectangle < 
   
      
         #   
      
         #{:xx=>nil, :yy=>nil, :ww=>nil, :hh=>nil}   
      
         #{:p=>nil, :s=>nil}   
      
         #{:topleft=>nil, :bottomright=>nil}   
      
   

   #FXRegion < 
   
      
         #   
      
         #{:r=>nil}   
      
         #{:rect=>nil}   
      
         #{:x=>nil, :y=>nil, :w=>nil, :h=>nil}   
      
         #{:points=>nil, :winding=>"false"}   
      
   

   #FXRegistry < FXSettings
   
      
         #{:appKey=>"\"\"", :vendorKey=>"\"\""}   
      
   

   #FXReplaceDialog < FXDialogBox
   
      
         #{:owner=>nil, :caption=>nil, :ic=>"nil", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXRootWindow < FXComposite
   
      
         #{:a=>nil, :vis=>nil}   
      
   

   #FXRuler < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"RULER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXRulerView < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #NotifyHeader < 
   
      #No initializer
   

   #SCNotification < 
   
      #No initializer
   

   #TextRange < 
   
      
         #{:start=>nil, :last=>nil, :size=>nil}   
      
   

   #FXScintilla < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXScrollArea < FXComposite
   
      
         #{:parent=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXScrollBar < FXWindow
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"SCROLLBAR_VERTICAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXScrollCorner < FXWindow
   
      
         #{:p=>nil}   
      
   

   #FXScrollPane < FXMenuPane
   
      
         #{:owner=>nil, :nvis=>nil, :opts=>"0"}   
      
   

   #FXScrollWindow < FXScrollArea
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXSearchDialog < FXReplaceDialog
   
      
         #{:owner=>nil, :caption=>nil, :ic=>"nil", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXSeparator < FXFrame
   
      
         #{:p=>nil, :opts=>"SEPARATOR_GROOVE|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXHorizontalSeparator < FXSeparator
   
      
         #{:p=>nil, :opts=>"SEPARATOR_GROOVE|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"1", :padRight=>"1", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXVerticalSeparator < FXSeparator
   
      
         #{:p=>nil, :opts=>"SEPARATOR_GROOVE|LAYOUT_FILL_Y", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"1", :padBottom=>"1"}   
      
   

   #FXSettings < FXDict
   
      
         #   
      
   

   #FXShell < FXComposite
   
      #No initializer
   

   #FXShutterItem < FXVerticalFrame
   
      
         #{:p=>nil, :text=>"\"\"", :icon=>"nil", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXShutter < FXVerticalFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXSize < 
   
      
         #   
      
         #{:s=>nil}   
      
         #{:ww=>nil, :hh=>nil}   
      
   

   #FXSlider < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"SLIDER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"0", :padRight=>"0", :padTop=>"0", :padBottom=>"0"}   
      
   

   #FXSphered < 
   
      
         #   
      
         #{:otherSphere=>nil}   
      
         #{:cen=>nil, :rad=>"0.0"}   
      
         #{:x=>nil, :y=>nil, :z=>nil, :rad=>"0.0"}   
      
         #{:bounds=>nil}   
      
   

   #FXSpheref < 
   
      
         #   
      
         #{:otherSphere=>nil}   
      
         #{:cen=>nil, :rad=>"0.0"}   
      
         #{:x=>nil, :y=>nil, :z=>nil, :rad=>"0.0"}   
      
         #{:bounds=>nil}   
      
   

   #FXSpinner < FXPacker
   
      
         #{:p=>nil, :cols=>nil, :target=>"nil", :selector=>"0", :opts=>"SPIN_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXSplashWindow < FXTopWindow
   
      
         #{:owner=>nil, :icon=>nil, :opts=>"SPLASH_SIMPLE", :ms=>"5000"}   
      
   

   #FXSplitter < FXComposite
   
      
         #{:p=>nil, :opts=>"SPLITTER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
         #{:p=>nil, :tgt=>nil, :sel=>nil, :opts=>"SPLITTER_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXSpring < FXPacker
   
      
         #{:p=>nil, :opts=>"0", :relw=>"0", :relh=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXStatusBar < FXHorizontalFrame
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"4", :vSpacing=>"0"}   
      
   

   #FXStatusLine < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0"}   
      
   

   #FXStream < 
   
      
         #{:cont=>"nil"}   
      
   

   #FXStringDict < FXDict
   
      
         #   
      
   

   #FXSwitcher < FXPacker
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING"}   
      
   

   #FXTGAIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXTGAImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXTIFIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXTIFImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXTabBar < FXPacker
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"TABBOOK_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING"}   
      
   

   #FXTabBook < FXTabBar
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"TABBOOK_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING"}   
      
   

   #FXTabItem < FXLabel
   
      
         #{:p=>nil, :text=>nil, :ic=>"nil", :opts=>"TAB_TOP_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXTablePos < 
   
      
         #   
      
   

   #FXTableRange < 
   
      
         #   
      
   

   #FXTableItem < FXObject
   
      
         #{:text=>nil, :icon=>"nil", :data=>"nil"}   
      
   

   #FXTable < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_MARGIN", :padRight=>"DEFAULT_MARGIN", :padTop=>"DEFAULT_MARGIN", :padBottom=>"DEFAULT_MARGIN"}   
      
   

   #FXHiliteStyle < 
   
      #No initializer
   

   #FXTextChange < 
   
      #No initializer
   

   #FXText < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2"}   
      
   

   #FXTextField < FXFrame
   
      
         #{:p=>nil, :ncols=>nil, :target=>"nil", :selector=>"0", :opts=>"TEXTFIELD_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXToggleButton < FXLabel
   
      
         #{:p=>nil, :text1=>nil, :text2=>nil, :icon1=>"nil", :icon2=>"nil", :target=>"nil", :selector=>"0", :opts=>"TOGGLEBUTTON_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXToolBar < FXDockBar
   
      
         #{:p=>nil, :q=>nil, :opts=>"LAYOUT_TOP|LAYOUT_LEFT|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
         #{:p=>nil, :opts=>"LAYOUT_TOP|LAYOUT_LEFT|LAYOUT_FILL_X", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"3", :padRight=>"3", :padTop=>"2", :padBottom=>"2", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXToolBarGrip < FXDockHandler
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"TOOLBARGRIP_SINGLE", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXToolBarShell < FXTopWindow
   
      
         #{:owner=>nil, :opts=>"FRAME_RAISED|FRAME_THICK", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :hSpacing=>"4", :vSpacing=>"4"}   
      
   

   #FXToolBarTab < FXFrame
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_RAISED", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXToolTip < FXShell
   
      
         #{:app=>nil, :opts=>"TOOLTIP_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXTopWindow < FXShell
   
      #No initializer
   

   #FXTranslator < 
   
      
         #{:a=>nil}   
      
   

   #FXTreeItem < FXObject
   
      
         #{:text=>nil, :openIcon=>"nil", :closedIcon=>"nil", :data=>"nil"}   
      
   

   #FXTreeList < FXScrollArea
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"TREELIST_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
   

   #FXTreeListBox < FXPacker
   
      
         #{:p=>nil, :target=>"nil", :selector=>"0", :opts=>"FRAME_SUNKEN|FRAME_THICK|TREELISTBOX_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXTriStateButton < FXToggleButton
   
      
         #{:p=>nil, :text1=>nil, :text2=>nil, :text3=>nil, :icon1=>"nil", :icon2=>"nil", :icon3=>"nil", :target=>"nil", :selector=>"0", :opts=>"TOGGLEBUTTON_NORMAL", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_PAD", :padRight=>"DEFAULT_PAD", :padTop=>"DEFAULT_PAD", :padBottom=>"DEFAULT_PAD"}   
      
   

   #FXVec2d < 
   
      
         #{:xx=>"0.0", :yy=>"0.0"}   
      
   

   #FXVec2f < 
   
      
         #{:xx=>"0.0", :yy=>"0.0"}   
      
   

   #FXVec3d < 
   
      
         #   
      
         #{:xx=>nil, :yy=>nil, :zz=>"1.0"}   
      
   

   #FXVec3f < 
   
      
         #   
      
         #{:xx=>nil, :yy=>nil, :zz=>"1.0"}   
      
   

   #FXVec4d < 
   
      
         #   
      
         #{:xx=>nil, :yy=>nil, :zz=>nil, :ww=>"1.0"}   
      
         #{:vec3d=>nil, :ww=>"1.0"}   
      
   

   #FXVec4f < 
   
      
         #   
      
         #{:xx=>nil, :yy=>nil, :zz=>nil, :ww=>"1.0"}   
      
         #{:vec3f=>nil, :ww=>"1.0"}   
      
   

   #FXVerticalFrame < FXPacker
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"DEFAULT_SPACING", :padRight=>"DEFAULT_SPACING", :padTop=>"DEFAULT_SPACING", :padBottom=>"DEFAULT_SPACING", :hSpacing=>"DEFAULT_SPACING", :vSpacing=>"DEFAULT_SPACING"}   
      
   

   #FXVisual < FXId
   
      
         #{:a=>nil, :flgs=>nil, :d=>"32"}   
      
   

   #FXWindow < FXDrawable
   
      
         #{:p=>nil, :opts=>"0", :x=>"0", :y=>"0", :width=>"0", :height=>"0"}   
      
         #{:a=>nil, :vis=>nil}   
      
         #{:a=>nil, :own=>nil, :opts=>nil, :x=>nil, :y=>nil, :w=>nil, :h=>nil}   
      
   

   #FXWizard < FXDialogBox
   
      
         #{:owner=>nil, :name=>nil, :image=>nil, :opts=>"DECOR_TITLE|DECOR_BORDER|DECOR_RESIZE", :x=>"0", :y=>"0", :width=>"0", :height=>"0", :padLeft=>"10", :padRight=>"10", :padTop=>"10", :padBottom=>"10", :hSpacing=>"10", :vSpacing=>"10"}   
      
   

   #FXXBMIcon < FXIcon
   
      
         #{:a=>nil, :pixels=>"nil", :mask=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXXBMImage < FXImage
   
      
         #{:a=>nil, :pixels=>"nil", :mask=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXXPMIcon < FXIcon
   
      
         #{:a=>nil, :pix=>"nil", :clr=>"0", :opts=>"0", :width=>"1", :height=>"1"}   
      
   

   #FXXPMImage < FXImage
   
      
         #{:a=>nil, :pix=>"nil", :opts=>"0", :width=>"1", :height=>"1"}   
      
   


module Fox
  module Enhancement
    module Mapper
      class << self
        def fox_classes
          Fox.constants.select { |k|
            Fox.const_get(k).instance_of? Class
          }
        end

        def fox_initialize_parms
          fox_classes.map { |klass|
            [klass, Fox.const_get(klass)
                .instance_method(:initialize)
                .parameters
                .map{ |typ, nam|
               unless typ == :rest
                 [typ, nam]
               else
                 [:rest,
                  parm_hints(klass).map{ |parm| [:req, parm] }
                 ]
               end
             }
            ]
          }
        end
         
        HINTS = {
        }
        
        def parm_hints klass
          HINTS[klass]
        end        
      end
    end
  end

# Here we include enhancements to all FXRuby classes

   class FX4Splitter
     include Enhancement
     attr_accessor :_o     
   end
   def fx4_splitter name = nil, &block
     o = OStruct.new

   end

   class FX7Segment
     include Enhancement
     attr_accessor :_o     
   end
   def fx7_segment name = nil, &block
     o = OStruct.new

   end

   class FXAccelTable
     include Enhancement
     attr_accessor :_o     
   end
   def fx_accel_table name = nil, &block
     o = OStruct.new

   end

   class FXEvent
     include Enhancement
     attr_accessor :_o     
   end
   def fx_event name = nil, &block
     o = OStruct.new

   end

   class FXApp
     include Enhancement
     attr_accessor :_o     
   end
   def fx_app name = nil, &block
     o = OStruct.new

   end

   class FXArrowButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_arrow_button name = nil, &block
     o = OStruct.new

   end

   class FXBMPIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxbmp_icon name = nil, &block
     o = OStruct.new

   end

   class FXBMPImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxbmp_image name = nil, &block
     o = OStruct.new

   end

   class FXBitmap
     include Enhancement
     attr_accessor :_o     
   end
   def fx_bitmap name = nil, &block
     o = OStruct.new

   end

   class FXBitmapFrame
     include Enhancement
     attr_accessor :_o     
   end
   def fx_bitmap_frame name = nil, &block
     o = OStruct.new

   end

   class FXBitmapView
     include Enhancement
     attr_accessor :_o     
   end
   def fx_bitmap_view name = nil, &block
     o = OStruct.new

   end

   class FXButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_button name = nil, &block
     o = OStruct.new

   end

   class FXCURCursor
     include Enhancement
     attr_accessor :_o     
   end
   def fxcur_cursor name = nil, &block
     o = OStruct.new

   end

   class FXCanvas
     include Enhancement
     attr_accessor :_o     
   end
   def fx_canvas name = nil, &block
     o = OStruct.new

   end

   class FXCheckButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_check_button name = nil, &block
     o = OStruct.new

   end

   class FXChoiceBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_choice_box name = nil, &block
     o = OStruct.new

   end

   class FXColorBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_bar name = nil, &block
     o = OStruct.new

   end

   class FXColorDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_dialog name = nil, &block
     o = OStruct.new

   end

   class FXColorItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_item name = nil, &block
     o = OStruct.new

   end

   class FXColorList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_list name = nil, &block
     o = OStruct.new

   end

   class FXColorRing
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_ring name = nil, &block
     o = OStruct.new

   end

   class FXColorSelector
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_selector name = nil, &block
     o = OStruct.new

   end

   class FXColorWell
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_well name = nil, &block
     o = OStruct.new

   end

   class FXColorWheel
     include Enhancement
     attr_accessor :_o     
   end
   def fx_color_wheel name = nil, &block
     o = OStruct.new

   end

   class FXComboBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_combo_box name = nil, &block
     o = OStruct.new

   end

   class FXComposite
     include Enhancement
     attr_accessor :_o     
   end
   def fx_composite name = nil, &block
     o = OStruct.new

   end

   class FXCursor
     include Enhancement
     attr_accessor :_o     
   end
   def fx_cursor name = nil, &block
     o = OStruct.new

   end

   class FXSegment
     include Enhancement
     attr_accessor :_o     
   end
   def fx_segment name = nil, &block
     o = OStruct.new

   end

   class FXArc
     include Enhancement
     attr_accessor :_o     
   end
   def fx_arc name = nil, &block
     o = OStruct.new

   end

   class FXDC
     include Enhancement
     attr_accessor :_o     
   end
   def fxdc name = nil, &block
     o = OStruct.new

   end

   class FXPSBounds
     include Enhancement
     attr_accessor :_o     
   end
   def fxps_bounds name = nil, &block
     o = OStruct.new

   end

   class FXPrinter
     include Enhancement
     attr_accessor :_o     
   end
   def fx_printer name = nil, &block
     o = OStruct.new

   end

   class FXDCPrint
     include Enhancement
     attr_accessor :_o     
   end
   def fxdc_print name = nil, &block
     o = OStruct.new

   end

   class FXDCWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fxdc_window name = nil, &block
     o = OStruct.new

   end

   class FXDataTarget
     include Enhancement
     attr_accessor :_o     
   end
   def fx_data_target name = nil, &block
     o = OStruct.new

   end

   class FXDebugTarget
     include Enhancement
     attr_accessor :_o     
   end
   def fx_debug_target name = nil, &block
     o = OStruct.new

   end

   class FXDelegator
     include Enhancement
     attr_accessor :_o     
   end
   def fx_delegator name = nil, &block
     o = OStruct.new

   end

   class FXDial
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dial name = nil, &block
     o = OStruct.new

   end

   class FXDialogBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dialog_box name = nil, &block
     o = OStruct.new

   end

   class FXDict
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dict name = nil, &block
     o = OStruct.new

   end

   class FXDirBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dir_box name = nil, &block
     o = OStruct.new

   end

   class FXDirDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dir_dialog name = nil, &block
     o = OStruct.new

   end

   class FXDirItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dir_item name = nil, &block
     o = OStruct.new

   end

   class FXDirList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dir_list name = nil, &block
     o = OStruct.new

   end

   class FXDirSelector
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dir_selector name = nil, &block
     o = OStruct.new

   end

   class FXDockBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dock_bar name = nil, &block
     o = OStruct.new

   end

   class FXDockHandler
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dock_handler name = nil, &block
     o = OStruct.new

   end

   class FXDockSite
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dock_site name = nil, &block
     o = OStruct.new

   end

   class FXDockTitle
     include Enhancement
     attr_accessor :_o     
   end
   def fx_dock_title name = nil, &block
     o = OStruct.new

   end

   class FXDocument
     include Enhancement
     attr_accessor :_o     
   end
   def fx_document name = nil, &block
     o = OStruct.new

   end

   class FXDragCorner
     include Enhancement
     attr_accessor :_o     
   end
   def fx_drag_corner name = nil, &block
     o = OStruct.new

   end

   class FXDrawable
     include Enhancement
     attr_accessor :_o     
   end
   def fx_drawable name = nil, &block
     o = OStruct.new

   end

   class FXDriveBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_drive_box name = nil, &block
     o = OStruct.new

   end

   class FXExtentd
     include Enhancement
     attr_accessor :_o     
   end
   def fx_extentd name = nil, &block
     o = OStruct.new

   end

   class FXExtentf
     include Enhancement
     attr_accessor :_o     
   end
   def fx_extentf name = nil, &block
     o = OStruct.new

   end

   class FXFileDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_dialog name = nil, &block
     o = OStruct.new

   end

   class FXFileAssoc
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_assoc name = nil, &block
     o = OStruct.new

   end

   class FXFileDict
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_dict name = nil, &block
     o = OStruct.new

   end

   class FXFileItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_item name = nil, &block
     o = OStruct.new

   end

   class FXFileList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_list name = nil, &block
     o = OStruct.new

   end

   class FXFileSelector
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_selector name = nil, &block
     o = OStruct.new

   end

   class FXFileStream
     include Enhancement
     attr_accessor :_o     
   end
   def fx_file_stream name = nil, &block
     o = OStruct.new

   end

   class FXFoldingItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_folding_item name = nil, &block
     o = OStruct.new

   end

   class FXFoldingList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_folding_list name = nil, &block
     o = OStruct.new

   end

   class FXFontDesc
     include Enhancement
     attr_accessor :_o     
   end
   def fx_font_desc name = nil, &block
     o = OStruct.new

   end

   class FXFont
     include Enhancement
     attr_accessor :_o     
   end
   def fx_font name = nil, &block
     o = OStruct.new

   end

   class FXFontDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_font_dialog name = nil, &block
     o = OStruct.new

   end

   class FXFontSelector
     include Enhancement
     attr_accessor :_o     
   end
   def fx_font_selector name = nil, &block
     o = OStruct.new

   end

   class FXFrame
     include Enhancement
     attr_accessor :_o     
   end
   def fx_frame name = nil, &block
     o = OStruct.new

   end

   class FXGIFCursor
     include Enhancement
     attr_accessor :_o     
   end
   def fxgif_cursor name = nil, &block
     o = OStruct.new

   end

   class FXGIFIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxgif_icon name = nil, &block
     o = OStruct.new

   end

   class FXGIFImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxgif_image name = nil, &block
     o = OStruct.new

   end

   class FXGLCanvas
     include Enhancement
     attr_accessor :_o     
   end
   def fxgl_canvas name = nil, &block
     o = OStruct.new

   end

   class FXGLContext
     include Enhancement
     attr_accessor :_o     
   end
   def fxgl_context name = nil, &block
     o = OStruct.new

   end

   class FXGLObject
     include Enhancement
     attr_accessor :_o     
   end
   def fxgl_object name = nil, &block
     o = OStruct.new

   end

   class FXGLShape
     include Enhancement
     attr_accessor :_o     
   end
   def fxgl_shape name = nil, &block
     o = OStruct.new

   end

   class FXViewport
     include Enhancement
     attr_accessor :_o     
   end
   def fx_viewport name = nil, &block
     o = OStruct.new

   end

   class FXLight
     include Enhancement
     attr_accessor :_o     
   end
   def fx_light name = nil, &block
     o = OStruct.new

   end

   class FXMaterial
     include Enhancement
     attr_accessor :_o     
   end
   def fx_material name = nil, &block
     o = OStruct.new

   end

   class FXGLViewer
     include Enhancement
     attr_accessor :_o     
   end
   def fxgl_viewer name = nil, &block
     o = OStruct.new

   end

   class FXGLVisual
     include Enhancement
     attr_accessor :_o     
   end
   def fxgl_visual name = nil, &block
     o = OStruct.new

   end

   class FXGradient
     include Enhancement
     attr_accessor :_o     
   end
   def fx_gradient name = nil, &block
     o = OStruct.new

   end

   class FXGradientBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_gradient_bar name = nil, &block
     o = OStruct.new

   end

   class FXGroupBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_group_box name = nil, &block
     o = OStruct.new

   end

   class FXHeaderItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_header_item name = nil, &block
     o = OStruct.new

   end

   class FXHeader
     include Enhancement
     attr_accessor :_o     
   end
   def fx_header name = nil, &block
     o = OStruct.new

   end

   class FXHorizontalFrame
     include Enhancement
     attr_accessor :_o     
   end
   def fx_horizontal_frame name = nil, &block
     o = OStruct.new

   end

   class FXICOIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxico_icon name = nil, &block
     o = OStruct.new

   end

   class FXICOImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxico_image name = nil, &block
     o = OStruct.new

   end

   class FXIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fx_icon name = nil, &block
     o = OStruct.new

   end

   class FXIconDict
     include Enhancement
     attr_accessor :_o     
   end
   def fx_icon_dict name = nil, &block
     o = OStruct.new

   end

   class FXIconItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_icon_item name = nil, &block
     o = OStruct.new

   end

   class FXIconList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_icon_list name = nil, &block
     o = OStruct.new

   end

   class FXIconSource
     include Enhancement
     attr_accessor :_o     
   end
   def fx_icon_source name = nil, &block
     o = OStruct.new

   end

   class FXId
     include Enhancement
     attr_accessor :_o     
   end
   def fx_id name = nil, &block
     o = OStruct.new

   end

   class FXImage
     include Enhancement
     attr_accessor :_o     
   end
   def fx_image name = nil, &block
     o = OStruct.new

   end

   class FXImageFrame
     include Enhancement
     attr_accessor :_o     
   end
   def fx_image_frame name = nil, &block
     o = OStruct.new

   end

   class FXImageView
     include Enhancement
     attr_accessor :_o     
   end
   def fx_image_view name = nil, &block
     o = OStruct.new

   end

   class FXInputDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_input_dialog name = nil, &block
     o = OStruct.new

   end

   class FXJPGIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxjpg_icon name = nil, &block
     o = OStruct.new

   end

   class FXJPGImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxjpg_image name = nil, &block
     o = OStruct.new

   end

   class FXKnob
     include Enhancement
     attr_accessor :_o     
   end
   def fx_knob name = nil, &block
     o = OStruct.new

   end

   class FXLabel
     include Enhancement
     attr_accessor :_o     
   end
   def fx_label name = nil, &block
     o = OStruct.new

   end

   class FXListItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_list_item name = nil, &block
     o = OStruct.new

   end

   class FXList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_list name = nil, &block
     o = OStruct.new

   end

   class FXListBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_list_box name = nil, &block
     o = OStruct.new

   end

   class FXMDIDeleteButton
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_delete_button name = nil, &block
     o = OStruct.new

   end

   class FXMDIRestoreButton
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_restore_button name = nil, &block
     o = OStruct.new

   end

   class FXMDIMaximizeButton
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_maximize_button name = nil, &block
     o = OStruct.new

   end

   class FXMDIMinimizeButton
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_minimize_button name = nil, &block
     o = OStruct.new

   end

   class FXMDIWindowButton
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_window_button name = nil, &block
     o = OStruct.new

   end

   class FXMDIMenu
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_menu name = nil, &block
     o = OStruct.new

   end

   class FXMDIChild
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_child name = nil, &block
     o = OStruct.new

   end

   class FXMDIClient
     include Enhancement
     attr_accessor :_o     
   end
   def fxmdi_client name = nil, &block
     o = OStruct.new

   end

   class FXMainWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fx_main_window name = nil, &block
     o = OStruct.new

   end

   class FXMatrix
     include Enhancement
     attr_accessor :_o     
   end
   def fx_matrix name = nil, &block
     o = OStruct.new

   end

   class FXMemoryBuffer
     include Enhancement
     attr_accessor :_o     
   end
   def fx_memory_buffer name = nil, &block
     o = OStruct.new

   end

   class FXMemoryStream
     include Enhancement
     attr_accessor :_o     
   end
   def fx_memory_stream name = nil, &block
     o = OStruct.new

   end

   class FXMenuBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_bar name = nil, &block
     o = OStruct.new

   end

   class FXMenuButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_button name = nil, &block
     o = OStruct.new

   end

   class FXMenuCaption
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_caption name = nil, &block
     o = OStruct.new

   end

   class FXMenuCascade
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_cascade name = nil, &block
     o = OStruct.new

   end

   class FXMenuCheck
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_check name = nil, &block
     o = OStruct.new

   end

   class FXMenuCommand
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_command name = nil, &block
     o = OStruct.new

   end

   class FXMenuPane
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_pane name = nil, &block
     o = OStruct.new

   end

   class FXMenuRadio
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_radio name = nil, &block
     o = OStruct.new

   end

   class FXMenuSeparator
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_separator name = nil, &block
     o = OStruct.new

   end

   class FXMenuTitle
     include Enhancement
     attr_accessor :_o     
   end
   def fx_menu_title name = nil, &block
     o = OStruct.new

   end

   class FXMessageBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_message_box name = nil, &block
     o = OStruct.new

   end

   class FXObject
     include Enhancement
     attr_accessor :_o     
   end
   def fx_object name = nil, &block
     o = OStruct.new

   end

   class FXOption
     include Enhancement
     attr_accessor :_o     
   end
   def fx_option name = nil, &block
     o = OStruct.new

   end

   class FXOptionMenu
     include Enhancement
     attr_accessor :_o     
   end
   def fx_option_menu name = nil, &block
     o = OStruct.new

   end

   class FXPCXIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxpcx_icon name = nil, &block
     o = OStruct.new

   end

   class FXPCXImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxpcx_image name = nil, &block
     o = OStruct.new

   end

   class FXPNGIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxpng_icon name = nil, &block
     o = OStruct.new

   end

   class FXPNGImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxpng_image name = nil, &block
     o = OStruct.new

   end

   class FXPPMIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxppm_icon name = nil, &block
     o = OStruct.new

   end

   class FXPPMImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxppm_image name = nil, &block
     o = OStruct.new

   end

   class FXPacker
     include Enhancement
     attr_accessor :_o     
   end
   def fx_packer name = nil, &block
     o = OStruct.new

   end

   class FXPicker
     include Enhancement
     attr_accessor :_o     
   end
   def fx_picker name = nil, &block
     o = OStruct.new

   end

   class FXPopup
     include Enhancement
     attr_accessor :_o     
   end
   def fx_popup name = nil, &block
     o = OStruct.new

   end

   class FXPrintDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_print_dialog name = nil, &block
     o = OStruct.new

   end

   class FXProgressBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_progress_bar name = nil, &block
     o = OStruct.new

   end

   class FXProgressDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_progress_dialog name = nil, &block
     o = OStruct.new

   end

   class FXQuatd
     include Enhancement
     attr_accessor :_o     
   end
   def fx_quatd name = nil, &block
     o = OStruct.new

   end

   class FXQuatf
     include Enhancement
     attr_accessor :_o     
   end
   def fx_quatf name = nil, &block
     o = OStruct.new

   end

   class FXRGBIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxrgb_icon name = nil, &block
     o = OStruct.new

   end

   class FXRGBImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxrgb_image name = nil, &block
     o = OStruct.new

   end

   class FXRadioButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_radio_button name = nil, &block
     o = OStruct.new

   end

   class FXRanged
     include Enhancement
     attr_accessor :_o     
   end
   def fx_ranged name = nil, &block
     o = OStruct.new

   end

   class FXRangef
     include Enhancement
     attr_accessor :_o     
   end
   def fx_rangef name = nil, &block
     o = OStruct.new

   end

   class FXRealSlider
     include Enhancement
     attr_accessor :_o     
   end
   def fx_real_slider name = nil, &block
     o = OStruct.new

   end

   class FXRealSpinner
     include Enhancement
     attr_accessor :_o     
   end
   def fx_real_spinner name = nil, &block
     o = OStruct.new

   end

   class FXRecentFiles
     include Enhancement
     attr_accessor :_o     
   end
   def fx_recent_files name = nil, &block
     o = OStruct.new

   end

   class FXRectangle
     include Enhancement
     attr_accessor :_o     
   end
   def fx_rectangle name = nil, &block
     o = OStruct.new

   end

   class FXRegion
     include Enhancement
     attr_accessor :_o     
   end
   def fx_region name = nil, &block
     o = OStruct.new

   end

   class FXRegistry
     include Enhancement
     attr_accessor :_o     
   end
   def fx_registry name = nil, &block
     o = OStruct.new

   end

   class FXReplaceDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_replace_dialog name = nil, &block
     o = OStruct.new

   end

   class FXRootWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fx_root_window name = nil, &block
     o = OStruct.new

   end

   class FXRuler
     include Enhancement
     attr_accessor :_o     
   end
   def fx_ruler name = nil, &block
     o = OStruct.new

   end

   class FXRulerView
     include Enhancement
     attr_accessor :_o     
   end
   def fx_ruler_view name = nil, &block
     o = OStruct.new

   end

   class NotifyHeader
     include Enhancement
     attr_accessor :_o     
   end
   def notify_header name = nil, &block
     o = OStruct.new

   end

   class SCNotification
     include Enhancement
     attr_accessor :_o     
   end
   def sc_notification name = nil, &block
     o = OStruct.new

   end

   class TextRange
     include Enhancement
     attr_accessor :_o     
   end
   def text_range name = nil, &block
     o = OStruct.new

   end

   class FXScintilla
     include Enhancement
     attr_accessor :_o     
   end
   def fx_scintilla name = nil, &block
     o = OStruct.new

   end

   class FXScrollArea
     include Enhancement
     attr_accessor :_o     
   end
   def fx_scroll_area name = nil, &block
     o = OStruct.new

   end

   class FXScrollBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_scroll_bar name = nil, &block
     o = OStruct.new

   end

   class FXScrollCorner
     include Enhancement
     attr_accessor :_o     
   end
   def fx_scroll_corner name = nil, &block
     o = OStruct.new

   end

   class FXScrollPane
     include Enhancement
     attr_accessor :_o     
   end
   def fx_scroll_pane name = nil, &block
     o = OStruct.new

   end

   class FXScrollWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fx_scroll_window name = nil, &block
     o = OStruct.new

   end

   class FXSearchDialog
     include Enhancement
     attr_accessor :_o     
   end
   def fx_search_dialog name = nil, &block
     o = OStruct.new

   end

   class FXSeparator
     include Enhancement
     attr_accessor :_o     
   end
   def fx_separator name = nil, &block
     o = OStruct.new

   end

   class FXHorizontalSeparator
     include Enhancement
     attr_accessor :_o     
   end
   def fx_horizontal_separator name = nil, &block
     o = OStruct.new

   end

   class FXVerticalSeparator
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vertical_separator name = nil, &block
     o = OStruct.new

   end

   class FXSettings
     include Enhancement
     attr_accessor :_o     
   end
   def fx_settings name = nil, &block
     o = OStruct.new

   end

   class FXShell
     include Enhancement
     attr_accessor :_o     
   end
   def fx_shell name = nil, &block
     o = OStruct.new

   end

   class FXShutterItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_shutter_item name = nil, &block
     o = OStruct.new

   end

   class FXShutter
     include Enhancement
     attr_accessor :_o     
   end
   def fx_shutter name = nil, &block
     o = OStruct.new

   end

   class FXSize
     include Enhancement
     attr_accessor :_o     
   end
   def fx_size name = nil, &block
     o = OStruct.new

   end

   class FXSlider
     include Enhancement
     attr_accessor :_o     
   end
   def fx_slider name = nil, &block
     o = OStruct.new

   end

   class FXSphered
     include Enhancement
     attr_accessor :_o     
   end
   def fx_sphered name = nil, &block
     o = OStruct.new

   end

   class FXSpheref
     include Enhancement
     attr_accessor :_o     
   end
   def fx_spheref name = nil, &block
     o = OStruct.new

   end

   class FXSpinner
     include Enhancement
     attr_accessor :_o     
   end
   def fx_spinner name = nil, &block
     o = OStruct.new

   end

   class FXSplashWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fx_splash_window name = nil, &block
     o = OStruct.new

   end

   class FXSplitter
     include Enhancement
     attr_accessor :_o     
   end
   def fx_splitter name = nil, &block
     o = OStruct.new

   end

   class FXSpring
     include Enhancement
     attr_accessor :_o     
   end
   def fx_spring name = nil, &block
     o = OStruct.new

   end

   class FXStatusBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_status_bar name = nil, &block
     o = OStruct.new

   end

   class FXStatusLine
     include Enhancement
     attr_accessor :_o     
   end
   def fx_status_line name = nil, &block
     o = OStruct.new

   end

   class FXStream
     include Enhancement
     attr_accessor :_o     
   end
   def fx_stream name = nil, &block
     o = OStruct.new

   end

   class FXStringDict
     include Enhancement
     attr_accessor :_o     
   end
   def fx_string_dict name = nil, &block
     o = OStruct.new

   end

   class FXSwitcher
     include Enhancement
     attr_accessor :_o     
   end
   def fx_switcher name = nil, &block
     o = OStruct.new

   end

   class FXTGAIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxtga_icon name = nil, &block
     o = OStruct.new

   end

   class FXTGAImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxtga_image name = nil, &block
     o = OStruct.new

   end

   class FXTIFIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxtif_icon name = nil, &block
     o = OStruct.new

   end

   class FXTIFImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxtif_image name = nil, &block
     o = OStruct.new

   end

   class FXTabBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tab_bar name = nil, &block
     o = OStruct.new

   end

   class FXTabBook
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tab_book name = nil, &block
     o = OStruct.new

   end

   class FXTabItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tab_item name = nil, &block
     o = OStruct.new

   end

   class FXTablePos
     include Enhancement
     attr_accessor :_o     
   end
   def fx_table_pos name = nil, &block
     o = OStruct.new

   end

   class FXTableRange
     include Enhancement
     attr_accessor :_o     
   end
   def fx_table_range name = nil, &block
     o = OStruct.new

   end

   class FXTableItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_table_item name = nil, &block
     o = OStruct.new

   end

   class FXTable
     include Enhancement
     attr_accessor :_o     
   end
   def fx_table name = nil, &block
     o = OStruct.new

   end

   class FXHiliteStyle
     include Enhancement
     attr_accessor :_o     
   end
   def fx_hilite_style name = nil, &block
     o = OStruct.new

   end

   class FXTextChange
     include Enhancement
     attr_accessor :_o     
   end
   def fx_text_change name = nil, &block
     o = OStruct.new

   end

   class FXText
     include Enhancement
     attr_accessor :_o     
   end
   def fx_text name = nil, &block
     o = OStruct.new

   end

   class FXTextField
     include Enhancement
     attr_accessor :_o     
   end
   def fx_text_field name = nil, &block
     o = OStruct.new

   end

   class FXToggleButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_toggle_button name = nil, &block
     o = OStruct.new

   end

   class FXToolBar
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tool_bar name = nil, &block
     o = OStruct.new

   end

   class FXToolBarGrip
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tool_bar_grip name = nil, &block
     o = OStruct.new

   end

   class FXToolBarShell
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tool_bar_shell name = nil, &block
     o = OStruct.new

   end

   class FXToolBarTab
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tool_bar_tab name = nil, &block
     o = OStruct.new

   end

   class FXToolTip
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tool_tip name = nil, &block
     o = OStruct.new

   end

   class FXTopWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fx_top_window name = nil, &block
     o = OStruct.new

   end

   class FXTranslator
     include Enhancement
     attr_accessor :_o     
   end
   def fx_translator name = nil, &block
     o = OStruct.new

   end

   class FXTreeItem
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tree_item name = nil, &block
     o = OStruct.new

   end

   class FXTreeList
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tree_list name = nil, &block
     o = OStruct.new

   end

   class FXTreeListBox
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tree_list_box name = nil, &block
     o = OStruct.new

   end

   class FXTriStateButton
     include Enhancement
     attr_accessor :_o     
   end
   def fx_tri_state_button name = nil, &block
     o = OStruct.new

   end

   class FXVec2d
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vec2d name = nil, &block
     o = OStruct.new

   end

   class FXVec2f
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vec2f name = nil, &block
     o = OStruct.new

   end

   class FXVec3d
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vec3d name = nil, &block
     o = OStruct.new

   end

   class FXVec3f
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vec3f name = nil, &block
     o = OStruct.new

   end

   class FXVec4d
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vec4d name = nil, &block
     o = OStruct.new

   end

   class FXVec4f
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vec4f name = nil, &block
     o = OStruct.new

   end

   class FXVerticalFrame
     include Enhancement
     attr_accessor :_o     
   end
   def fx_vertical_frame name = nil, &block
     o = OStruct.new

   end

   class FXVisual
     include Enhancement
     attr_accessor :_o     
   end
   def fx_visual name = nil, &block
     o = OStruct.new

   end

   class FXWindow
     include Enhancement
     attr_accessor :_o     
   end
   def fx_window name = nil, &block
     o = OStruct.new

   end

   class FXWizard
     include Enhancement
     attr_accessor :_o     
   end
   def fx_wizard name = nil, &block
     o = OStruct.new

   end

   class FXXBMIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxxbm_icon name = nil, &block
     o = OStruct.new

   end

   class FXXBMImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxxbm_image name = nil, &block
     o = OStruct.new

   end

   class FXXPMIcon
     include Enhancement
     attr_accessor :_o     
   end
   def fxxpm_icon name = nil, &block
     o = OStruct.new

   end

   class FXXPMImage
     include Enhancement
     attr_accessor :_o     
   end
   def fxxpm_image name = nil, &block
     o = OStruct.new

   end

end 
